apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-45ku
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-45ku
    app.kubernetes.io/part-of: load-app-428eec29-13fc-40d5-b2cd-682f8cf9de32
  name: devfile-sample-45ku
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-45ku
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-45ku
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-81-tenant/load-app-428eec29-13fc-40d5-b2cd-682f8cf9de32/devfile-sample-45ku@sha256:397eae124f04ef80e5f8a08a8b13dc17379579c28306af658a1003db956f6b8f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
